### ISSUE TITLE
if statement issue

### ISSUE THREAD

**Issue by goatmale** [derekrprice/k8s-hacks#1]
Derek, I tested your script after adapting it into a bash script in testing this fix. I'm seeing issues with `-f` in the if statement when testing manually not finding the pod directory and not preventing running pods from having their cgroups stopped.

```
#assign a random pod guid from the running pods.
pod=28aa84d1-e6e0-11e9-8a72-000d3a010a35
#check the pod folder actually exists:
cd /var/lib/kubelet/pods/$pod
:/var/lib/kubelet/pods/28aa84d1-e6e0-11e9-8a72-000d3a010a35#

#Test using the -f switch to check if the folder exists.
[ -f "/var/lib/kubelet/pods/$pod" ] && echo "It exists!"


#Test using the -d switch to check if the folder exists.
[ -d "/var/lib/kubelet/pods/$pod" ] && echo "It exists!"
It exists!

#Test using the -e switch to check if the file exists.
[ -e "/var/lib/kubelet/pods/$pod" ] && echo "It exists!"
It exists!

```
Also, i'm not sure that the `'`s are needed to escape `'$pod'`

`-e` seems to be a better fix as this checks both directories and files.
http://tldp.org/LDP/abs/html/fto.html

**Comment by derekrprice** [comment]
@goatmale, thanks for the report and patch!
